import { Router } from 'express';
import { authGuard } from '../middleware/authGuard';
import { generatePost, analyzeContent, generateCalendar, getPosts, savePost, updatePost, uploadAndGeneratePosts, scheduleBatch } from '../controllers/contentController';
import { generatePostImage, generateImageOptions } from '../controllers/imageController';
import { upload } from '../services/upload';
import { publishPost } from '../controllers/publishController';

const router = Router();
router.use(authGuard);
router.post('/generate', generatePost);
router.post('/analyze', analyzeContent);
router.post('/calendar', generateCalendar);
router.post('/upload-material', upload.single('file'), uploadAndGeneratePosts);
router.post('/generate-image', generatePostImage);
router.post('/generate-image-options', generateImageOptions);
router.get('/posts', getPosts);
router.post('/posts', savePost);
router.patch('/posts/:id', updatePost);
router.post('/posts/schedule-batch', scheduleBatch);
router.post('/publish', publishPost);
export default router;
